Update ci-cd.yml

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -20,4 +20,13 @@ jobs:
       run: dotnet build --no-restore OnlineShopAPI/OnlineShopAPI/OnlineShopAPI.csproj
     - name: Build IdentityServer
       run: dotnet build --no-restore OnlineShopAPI/IdentityServer/IdentityServer.csproj
+    - name: Run Tests
+      run: dotnet test --logger "trx;LogFileName=test-results.trx" OnlineShopAPI/OnlineShopAPI.sln
+    - name: Test Report
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: CoreAPI and IdentityServer Tests # Name of the check run which will be created
+        path: test-results.trx    # Path to test results
+        reporter: dotnet-trx        # Format of test results
     
